name: Run Tests

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
    # verificar o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # instalar o Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.24.3

    - name: Install dependencies
      run: flutter pub get
        
    # rodar os testes
    - name: Run tests
      run: flutter test --coverage

      
